name: whoami

services:
  whoami:
    # ------------ Identität ------------------------
    image: traefik/whoami:v1.11.0@sha256:200689790a0a0ea48ca45992e0450bc26ccab5307375b41c84dfc4f2475937ab
    container_name: whoami

    # ------------ Abhängigkeiten & Start -----------
    init: true
    restart: on-failure:3
    stop_grace_period: 10s

    # ----------- Ressourcen -----------
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: 6M
          pids: 16
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

    # ----------- Sicherheit -----------
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    # ----------- Speicher -----------
    read_only: true

    # ---------- Environment -----------
    environment:
      TZ: Europe/Berlin
