# Project Name
name: example

services:
  example:
    # ------------ Identität ------------------------
    image: nginx:alpine
    # Name des Containers
    container_name: example
    # definiert einen custom Host Name für den Container, der innerhalb des Containers verwendet wird.
    hostname: example
    # Definiert zusätzliche Suchdomänen für die DNS-Auflösung im Container
    dns_search:
      - example.com
    # Definiert den DNS Namen
    domainname: example.com


    # ------------ Abhängigkeiten & Start -----------
    # startet den Container mit einem init-Prozess, um die ordnungsgemäße Signalweiterleitung und Prozessverwaltung zu gewährleisten.
    init: true
    # Überschreibt den Standardbefehl des Images
    command:
      - nginx -g "daemon off;"
    # Neustart-Policy für den Container, um sicherzustellen, dass er automatisch neu gestartet wird, wenn er unerwartet stoppt oder abstürzt.
    # no: Der Container wird nicht automatisch neu gestartet.
    # always: Der Container wird immer neu gestartet, unabhängig von der Ursache des Stopps.
    # on-failure:[max-retries]: Der Container wird nur neu gestartet, wenn er mit einem Fehlercode
    # unless-stopped: Der Container wird neu gestartet, es sei denn, er wurde manuell gestoppt.
    restart: on-failure:3
    # Wartezeit nach Stop signal, bevor Kill gesendet wird, um dem Container Zeit zu geben, ordnungsgemäß herunterzufahren und Ressourcen freizugeben.
    stop_grace_period: 1m
    # prüft die Gesundheit des Containers, um sicherzustellen, dass er ordnungsgemäß funktioniert und erreichbar ist
    healthcheck:
      # definiert den Befehl, der ausgeführt wird, um die Gesundheit des Containers zu überprüfen.
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    # Steuert die Abhängigkeiten zwischen Services (Start und Stop Reihenfolge)
    depends_on:
      db:
        # automatischer Neustart des abhängigen Service, wenn er aktualisiert wurde.
        restart: true
        # definiert die Bedingung, unter der der abhängige Service als "bereit" gilt
        # service_started: Der abhängige Service muss gestartet sein, aber es wird nicht überprüft, ob er tatsächlich funktionsfähig ist.
        # service_healthy: Der abhängige Service muss den Gesundheitscheck bestehen, um als bereit zu gelten.
        # service_completed_successfully: Der abhängige Service muss erfolgreich abgeschlossen sein.
        condition: service_healthy
        # Bei False wird nur gewarnt, dass der abhängige Service nicht bereit ist, aber der Start des aktuellen Services wird trotzdem fortgesetzt.
        required: true


    # ----------- Ressourcen -----------
    # begrenzt die Anzahl der nutzbaren CPUs für den Service-Container
    cpu_count: 1
    # begrenzt die CPU-Nutzung auf 5% der verfügbaren CPU-Leistung
    cpu_percent: 5
    # max. RAM Nutzung
    mem_limit: 100M
    # reservierter RAM bei Start
    mem_reservation: 50M
    # gesamter RAM --> 1G = 100M im RAM und 900M im Swap
    # 0 = ignoriert
    memswap_limit: 1G
    # Container darf bei RAM Mangel nicht automatisch getötet werden
    oom_kill_disable: true
    # Priorität bei OOM Killer (niedriger Wert = höhere Priorität, Standard: 0, Bereich: -1000 bis 1000)
    oom_score_adj: -100
    # begrenzt die Anzahl der Prozesse, die ausgeführt werden können
    pids_limit: 20
    # TODO: Überschreibt ulimits für einen Container
    # https://docs.docker.com/reference/cli/docker/container/run/#set-ulimits-in-container---ulimit
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    # Logging begrenzen
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3


    # ----------- Sicherheit -----------
    # überschreibt den Benutzer, mit dem der Container läuft
    user: 99:100
    # deaktiviert bestimmte Privilegien und Funktionen
    # https://docs.docker.com/reference/cli/docker/container/run/#security-opt
    # Seccomp: Restrict syscalls to the minimum required for your container. Use Docker’s default seccomp profile as a starting point and customize per workload. Docker Seccomp
    # AppArmor: Apply per-container AppArmor profiles to enforce mandatory access controls
    security_opt:
      - no-new-privileges:true
      - seccomp=default
    # entfernt alle Linux-Kapazitäten und fügt nur notwendige hinzu
    # https://dockerlabs.collabnix.com/advanced/security/capabilities/
    # https://man7.org/linux/man-pages/man7/capabilities.7.html
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN


    # ----------- Netzwerk -----------
    # Netzwerkmodus des Containers (verbietet `networks` attribute)
    # bridge: verbindet mit bridge Network
    # none: Schaltet alle Container Netzwerke aus
    # host: Container hat Zugriff auf Host Netzwerk interface
    network_mode: bridge
    # Ohne Angabe wird default Netzwerk genutzt
    networks:
      basic:
        # Definiert Aliase, unter dem der Service im Netzwerk erreichbar ist
        aliases:
          - absolute.example
    ports:
      - name: web
        target: 80
        host_ip: 127.0.0.1
        published: "8080"
        protocol: tcp
        app_protocol: http
        mode: host
      - name: web-secured
        target: 443
        host_ip: 127.0.0.1
        published: "8083-9000"
        protocol: tcp
        app_protocol: https
        mode: host
    # Definiert die DNS Server, die der Container verwenden soll, anstelle der Standard-DNS-Server des Hosts
    dns:
      - 8.8.8.8
    # Definiert zusätzliche Optionen für die DNS-Auflösung im Container
    dns_opt:
      - use-vc


    # ----------- Speicher -----------
    # Definiert die Geräte, die dem Container zur Verfügung stehen sollen, und wie sie im Container gemountet werden sollen
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    # Read-Only-Dateisystem
    # vorher mit docker diff prüfen, welche Dateien/Verzeichnisse im Container geändert werden
    # https://tmp.bearblog.dev/secure-filesystem-in-docker/
    read_only: true
    # Mountet ein temporäres Dateisystem im Container
    # rw erlaubt Schreibzugriff
    # noexec verhindert die Ausführung von Binärdateien
    # nosuid blockiert das Setzen von SUID/SGID-Bits
    # size begrenzt den verfügbaren Speicherplatz (z.B. 64 MB für /tmp)
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=64m
      - /data:mode=755,uid=1009,gid=1009
      - /run
    # Mounts von host Pfaden oder volumes
    # type: volume, bind, tmpfs, image, npipe, cluster
    # source: Pfad auf Host bei bind, Docker Image bei image, Volumename bei volume, nicht bei tmpfs
    # target: Pfad im Container
    # read_only:
    # bind:
    #   propagation: Propagationsmodus
    #   create_host_path: Erstellt nötigen Host-Pfad, wenn er nicht existiert (true/false)
    #   selinux: SELinux-Label für den Mount (z.B. "z" (shared) oder "Z" (private))
    # volume:
    #   nocopy: Verhindert das Kopieren von Daten in das Volume, wenn es zum ersten Mal erstellt wird (true/false)
    #   subpath: Unterverzeichnis im Volume, das gemountet werden soll
    # tmpfs:
    #   size: Größe des tmpfs (z.B. "64m" für 64 Megabyte)
    #   mode: Berechtigungen für das tmpfs (z.B. "1777" für rwx für alle mit Sticky Bit)
    # image:
    #   subpath: Unterverzeichnis im Image, das gemountet werden soll
    volumes:
      - type: volume
        source: db-data
        target: /data
        read_only: false
        volume:
          nocopy: true
          subpath: sub
      - type: bind
        source: /var/run/postgres/postgres.sock
        target: /var/run/postgres/postgres.sock


    # ---------- Environment -----------
    # Definiert die Datei/-en mit den Umgebungsvariablen, die in den Container geladen werden sollen
    env_file:
      - path: ./defaul.env
        required: true
    # Definiert die Umgebungsvariablen, die in den Container geladen werden sollen
    environment:
      TZ: Europe/Berlin


    # ---------- Labels ----------------
    # definiert benutzerdefinierte Metadaten für den Container, die von anderen Tools oder Diensten verwendet werden können.
    labels:
      com.example.description: "This is an example service"






networks:
  # wenn kein Netzwerk angegeben ist, kann default modifiziert werden
  default:
    name: example_default
    driver_opts: # pass options to driver for network creation
      com.docker.network.bridge.host_binding_ipv4: 127.0.0.1
  # custom network
  basic:
  advanced:
    # bridge: Standardnetzwerk
    # host: Kein Netzwerktrenner zum Host
    # ipvlan: Container im VLAN des Hosts
    # macvlan: Container erscheinen als eigene Geräte im Netzwerk
    # none: Kein Netzwerkzugriff
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
  # externes Netzwerk
  outside:
    external: true
  # Rein intern erreichbares Netzwerk (Standard von außen erreichbar)
  inside:
    internal: true

volumes:
  # benannte Volumes
  data:
    name: example_data
  # benanntes Volume mit bind auf Host-Verzeichnis
  appdata:
    name: example_appdata
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/user/appdata/example
