# ingress-internal - Bindungen an die Rollen aus ../TraefikRBAC.yaml
#
# Den ServiceAccount `traefik-internal` legt das Chart an.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-cluster-internal
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-cluster
subjects:
  - kind: ServiceAccount
    name: traefik-internal
    namespace: traefik-internal

---
# Je bedientem Namespace eine Bindung.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-namespaced-internal
  namespace: traefik-internal
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-namespaced
subjects:
  - kind: ServiceAccount
    name: traefik-internal
    namespace: traefik-internal

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-namespaced-internal
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-namespaced
subjects:
  - kind: ServiceAccount
    name: traefik-internal
    namespace: traefik-internal

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-namespaced-internal
  namespace: headlamp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-namespaced
subjects:
  - kind: ServiceAccount
    name: traefik-internal
    namespace: traefik-internal

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-namespaced-internal
  namespace: whoami
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-namespaced
subjects:
  - kind: ServiceAccount
    name: traefik-internal
    namespace: traefik-internal
