# crowdsec - ServiceAccount
---
# Agent und LAPI sprechen die Kubernetes-API nie an
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: crowdsec
automountServiceAccountToken: false
