# die beiden Ingress-Controller, CrowdSec und die LoadBalancer-IPs.
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: network
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  path: ./k8s/flux/network
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    # Wegen CrowdSec
    - name: cert-manager-issuers
  prune: true
  timeout: 5m
