# USER
#   Format: <user>:<bcrypt-hash>:<role>
#   Rollen: admin | user
#   Hinweis: In docker-compose müssen `$` im bcrypt Hash als `$$` escaped werden.
#   Beispiel:
#     USER=test:$$2a$$12$$...:admin
#
# ACCESS
#   Format: <user>:<topic>:<permissions>
#   Topic: `*` als Wildcard (z.B. test:*:ro)
#   Permissions: rw | ro | wo | none
#   Beispiel:
#     ACCESS=test:*:rw

services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    restart: unless-stopped
    command:
      - serve
    environment:
      TZ: Europe/Berlin
      # https://docs.ntfy.sh/config/
      NTFY_BASE_URL: ntfy.nico-steinmueller.de
      NTFY_BEHIND_PROXY: true
      NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_ATTACHMENT_CACHE_DIR: /var/cache/ntfy/attachments
      NTFY_CACHE_FILE: /var/cache/ntfy/cache.db
      NTFY_CACHE_DURATION: 30d
      NTFY_ATTACHMENT_FILE_SIZE_LIMIT: 50M
      NTFY_ATTACHMENT_TOTAL_SIZE_LIMIT: 20G
      NTFY_ATTACHMENT_EXPIRY_DURATION: 30d
      NTFY_ENABLE_LOGIN: true
      # <user>:<bcrypt hash>:<role>,...
      # roles: admin, user
      # bcrypt hash with cost >=14
      # replace $ with $$ in the hash, because of docker-compose parsing
      NTFY_AUTH_USERS: ${USER:- test:$$2a$$12$$CS.XOcL53ym6XWYvasqME./zw7TpJlKwi4lWgeuc0Ufr40WJPyOwu:admin}
      # <user>:<topic>:<permissions>,...
      # Topic: * als wildcard, z.B. test:*:ro
      # Permissions: rw=read/write, ro=read-only, wo=write-only, none=deny-all
      NTFY_AUTH_ACCESS: ${ACCESS:-test:*:rw}
      # https://docs.ntfy.sh/config/#access-tokens
      # TODO: https://docs.ntfy.sh/config/#monitoring
    volumes:
      - /mnt/user/appdata/ntfy/cache:/var/cache/ntfy
      - /mnt/user/appdata/ntfy/attachments:/var/cache/ntfy/attachments
      - /mnt/user/appdata/ntfy/lib:/var/lib/ntfy
    networks:
      - proxy
    init: true # needed, if healthcheck is used. Prevents zombie processes
    healthcheck: # optional: remember to adapt the host:port to your environment
      test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      traefik.enable: true
      traefik.http.routers.ntfy.rule: Host(`ntfy.nico-steinmueller.de`)
      traefik.http.routers.ntfy.entrypoints: websecure
      traefik.http.routers.ntfy.middlewares: crowdsec@file, local-only@file
      traefik.http.routers.ntfy.service: ntfy
      traefik.http.services.ntfy.loadbalancer.server.port: 80


networks:
  proxy:
    external: true