---
- hosts: localhost
  tasks:
    - name: copy source VM template file
      copy:
        src: /var/lib/libvirt/images/ubuntu-24.04LTS-noble-server-template.qcow2
        dest: /var/lib/libvirt/images/{{ item.name }}.qcow2
      loop: "{{ vms }}"
    - name: create VMs
      virt:
        name: "{{ item.name }}"
        command: define
        xml: "{{ lookup('template', 'vm-template.xml.j2') }}"
      loop: "{{ vms }}"