name: navidrome

services:
  navidrome:
    # ------------ Identität ------------------------
    image: deluan/navidrome:0.61.2@sha256:9fa40b3d8dec43ceb2213d1fa551da3dcfef6ac6d19c2e534efb92527c2bafd2
    container_name: navidrome

    # ------------ Abhängigkeiten & Start -----------
    init: true
    restart: on-failure:3
    stop_grace_period: 30s
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:4533/ping || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

    # ----------- Ressourcen -----------
    deploy:
        resources:
          limits:
            cpus: 0.5
            memory: 128M
            pids: 16
          reservations:
            memory: 15M
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

    # ----------- Sicherheit -----------
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    # ----------- Speicher -----------
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=32m

    # ---------- Environment -----------
    environment:
      TZ: Europe/Berlin
      # https://www.navidrome.org/docs/usage/configuration/options/
      ND_LOGLEVEL: info
      # Anonymous Data Collection
      ND_ENABLEINSIGHTSCOLLECTOR: false
      ND_DEEZER_LANGUAGE: de
      ND_DEFAULTLANGUAGE: de
      ND_DEFAULTSHAREEXPIRATION: 24h
      ND_ENABLEARTWORKUPLOAD: false
      # false = disable all external intigations (anonymous data collection, nice login background images)
      ND_ENABLEEXTERNALSERVICES: false
      ND_INSPECT_ENABLED: false
      ND_LASTFM_LANGUAGE: de
      # TODO: Prometheus Metrics unter /metrics evtl. blockieren
      ND_PROMETHEUS_ENABLED: false
      ND_DATAFOLDER: /data
      ND_MUSICFOLDER: /music
      # ND_PROMETHEUS_PASSWORD
      # https://www.navidrome.org/docs/usage/admin/backup/
      ND_BACKUP_PATH: /backup
      ND_BACKUP_SCHEDULE: "0 0 * * *"
      ND_BACKUP_COUNT: 7
