# Env
# - PASSWORDENCRYPTIONKEY

services:
  navidrome:
    image: deluan/navidrome:0.61.2@sha256:9fa40b3d8dec43ceb2213d1fa551da3dcfef6ac6d19c2e534efb92527c2bafd2
#    user: 1000:1000 # should be owner of volumes
#    ports:
#      - "4533:4533"
    restart: unless-stopped
    environment:
      # https://www.navidrome.org/docs/usage/configuration/options/
      ND_LOGLEVEL: info
      ND_BASEURL: https://music.nico-steinmueller.de
      # Anonymous Data Collection
      ND_ENABLEINSIGHTSCOLLECTOR: false
      ND_DEEZER_LANGUAGE: de
      ND_DEFAULTLANGUAGE: de
      ND_DEFAULTSHAREEXPIRATION: 24h
      ND_ENABLEARTWORKUPLOAD: false
      # false = disable all external intigations (anonymous data collection, nice login background images)
      ND_ENABLEEXTERNALSERVICES: false
      ND_INSPECT_ENABLED: false
      ND_LASTFM_LANGUAGE: de
      # https://www.navidrome.org/docs/usage/admin/security/#encrypted-passwords
      # Darf nicht geändert werden.
      ND_PASSWORDENCRYPTIONKEY: ${PASSWORDENCRYPTIONKEY}
      # Prometheus Metrics unter /metrics evtl. blockieren
      ND_PROMETHEUS_ENABLED: false
      # ND_PROMETHEUS_PASSWORD
      # https://www.navidrome.org/docs/usage/admin/backup/
      ND_BACKUP_PATH: /backup
      ND_BACKUP_SCHEDULE: "0 0 * * *"
      ND_BACKUP_COUNT: 7
    volumes:
      # appdata
      - /mnt/user/appdata/navidrome/data:/data
      - /mnt/user/appdata/navidrome/backup:/backup
      # data
      - /mnt/user/data/music:/music:ro
    labels:
      traefik.enable: true
      traefik.http.routers.ntfy.rule: Host(`music.nico-steinmueller.de`)
      traefik.http.routers.ntfy.entrypoints: websecure
      traefik.http.routers.ntfy.middlewares: crowdsec@file, local-only@file
      traefik.http.routers.ntfy.service: ntfy
      traefik.http.services.ntfy.loadbalancer.server.port: 4533
