# docker-compose.yml
services:
  traefik:
    image: traefik:v3.6.8
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

    networks:
      - proxy
      - bond0

    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "443:443/tcp"
      - "8080:8080"

    environment:
      # IONOS DNS Challenge
      # API Key erstellen unter: https://developer.hosting.ionos.de/keys
      # Nur Berechtigung TXT-Record (DNS) erforderlich (kein Zugriff auf z.B. A-Records oder andere Ressourcen notwendig)
      IONOS_API_KEY: ${IONOS_API_KEY}

      TZ: Europe/Berlin

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
      - ./config/traefik.yml:/traefik.yml:ro # TODO: auf Server Pfad anpassen
      - ./logs:/logs # TODO: auf Server Pfad anpassen

volumes:
  letsencrypt:

networks:
  proxy:
    # TODO: evtl. direkt anlegen mit "docker network create proxy" und dann hier "external: true" setzen
    name: proxy
  bond0:
    external: true