# docker-compose.yml
#
# Umgebungsvariablen:
# ┌──────────────────┬────────────────────────────────┬──────────────────────────────────────────┐
# │ Variable         │ Beispiel                       │ Erklärung                                │
# ├──────────────────┼────────────────────────────────┼──────────────────────────────────────────┤
# │ IONOS_API_KEY    │ abc123def456ghi789...          │ API-Key für IONOS DNS Challenge          │
# │ TRAEFIK_LOCATION │ ./config                       │ Pfad zur Traefik-Hauptkonfiguration      │
# └──────────────────┴────────────────────────────────┴──────────────────────────────────────────┘
#
services:
  traefik:
    image: traefik:v3.6.8
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

    networks:
      - proxy
      - bond0
#      - monitoring

    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "443:443/tcp"
      - "8080:8080"

    environment:
      # IONOS DNS Challenge
      # API Key erstellen unter: https://developer.hosting.ionos.de/keys
      # Nur Berechtigung TXT-Record (DNS) erforderlich (kein Zugriff auf z.B. A-Records oder andere Ressourcen notwendig)
      IONOS_API_KEY: ${IONOS_API_KEY}

      TZ: Europe/Berlin

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
      - ${TRAEFIK_LOCATION:-./config}/traefik.yml:/traefik.yml:ro
      - ${TRAEFIK_LOCATION:-./config}/dynamic:/config/dynamic:ro
      - ${TRAEFIK_LOCATION:-.}/logs:/logs

    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  letsencrypt:

networks:
  proxy:
    # TODO: evtl. direkt anlegen mit "docker network create proxy" und dann hier "external: true" setzen
    name: proxy
  bond0:
    external: true
#  monitoring:
#    external: true
