services:

  whoami:
    image: traefik/whoami
    container_name: whoami
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`who.nico-steinmueller.de`)
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.middlewares=local-only@file

      - traefik.http.services.whoami.loadbalancer.server.port=80


networks:
  proxy:
    external: true