services:
  nextcloud:
    environment:
      PUID: 99
      PGID: 100
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      default:
      proxy:
    volumes:
      - type: bind
        source: /mnt/user/appdata/nextcloud/config
        target: /config
        read_only: false
        bind:
          create_host_path: false
      - type: bind
        source: /mnt/user/data/nextcloud/data
        target: /data
        read_only: false
        bind:
          create_host_path: false
      - type: bind
        source: /mnt/user/data/paperless/consume
        target: /app/www/public/paperless-consume
        read_only: false
        bind:
          create_host_path: false
    labels:
      traefik.enable: true
      traefik.http.routers.nextcloud.rule: Host(`cloud.nico-steinmueller.de`)
      traefik.http.routers.nextcloud.entrypoints: websecure
      traefik.http.routers.nextcloud.middlewares: crowdsec@file, compress@file
      traefik.http.routers.nextcloud.service: nextcloud
      traefik.http.services.nextcloud.loadbalancer.server.port: 8443
      traefik.http.services.nextcloud.loadbalancer.servertransport: nextcloud-transport
      traefik.http.services.nextcloud.loadbalancer.server.scheme: https

      traefik.http.serverTransports.nextcloud-transport.insecureSkipVerify: true
  database:
    user: 99:100
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - type: bind
        source: /mnt/user/appdata/nextcloud/postgres
        target: /var/lib/postgresql
        read_only: false
        bind:
          create_host_path: false
  redis:
    user: 99:100

networks:
  proxy:
    external: true