# WARNING: To install Immich, follow our guide: https://docs.immich.app/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#
# https://docs.immich.app/install/environment-variables
# Environment variables:
#   DB_PASSWORD: Password for the Postgres database user (default: postgres)
#   UPLOAD_LOCATION: Location to store Immich data (default: ./immich-data
#                     relative to the location of this docker-compose.yml file)

name: immich

services:
  immich-server:
    container_name: immich_server
    # https://github.com/immich-app/immich/pkgs/container/immich-server
    image: ghcr.io/immich-app/immich-server:v2.5.2@sha256:8ac5a6d471fbb6fcfec6bc34854dd5a947c1795547f0d9345d9bf1803d1209e3
    volumes:
      - ${UPLOAD_LOCATION:-./immich-data}:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      # Please use only the characters `A-Za-z0-9`, without special characters or spaces
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
      TZ: Europe/Berlin
    ports:
      - '34517:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # https://github.com/immich-app/immich/pkgs/container/immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v2.5.2@sha256:531d2bccbe20d0412496e36455715a18d692911eca5e2ee37d32e1e4f50e14bb
    volumes:
      - model-cache:/cache
    restart: always
    healthcheck:
      disable: false

  redis:
#    TODO: evtl. Update to alpine version later
    container_name: immich_redis
    image: docker.io/valkey/valkey:9.0.1-trixie@sha256:546304417feac0874c3dd576e0952c6bb8f06bb4093ea0c9ca303c73cf458f63
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    # https://github.com/immich-app/base-images/pkgs/container/postgres/versions?filters%5Bversion_type%5D=tagged
    image: ghcr.io/immich-app/postgres:18-vectorchord0.5.3-pgvector0.8.1@sha256:4d69da6e90cbaae3ddca1cd244e717a6e421488aaaf4fb8264d46c617ac9b5a2
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - postgres:/var/lib/postgresql
    shm_size: 128mb
    restart: always

volumes:
  model-cache:
  postgres:
