# Project Name
name: example

services:
  example:
    # ------------ Identität ------------------------
    image: nginx:alpine@sha256:1a8724a52d432501548a8d8681bb1554c2d09778f8b9ed0882fc3442549980b7
    container_name: example

    # ------------ Abhängigkeiten & Start -----------
    # für ordentliche Signalweiterleitung und Prozessverwaltung
    init: true
    # Überschreibt den Standardbefehl des Images
    command:
      - nginx -g "daemon off;"
    restart: unless-stopped
    # Wartezeit nach Stop signal vor Kill
    stop_grace_period: 1m
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    depends_on:
      db:
        # automatischer Neustart des abhängigen Service, wenn er aktualisiert wurde.
        restart: true
        # service_started, service_healthy, service_completed_successfully
        condition: service_healthy
        required: true


    # ----------- Ressourcen -----------
    # docker stats <container_name> zeigt die aktuelle Ressourcennutzung an
    deploy:
      resources:
        limits:
          # max. 0.5 Kerne der CPU
          cpus: 0.5
          # max. RAM Nutzung
          memory: 100M
          # begrenzt die Anzahl der Prozesse, die ausgeführt werden können
          pids: 32
        reservations:
          # reservierte CPU-Kerne
          cpus: 0.25
          # reservierter RAM
          memory: 50M
    # Logging begrenzen
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3


    # ----------- Sicherheit -----------
    # deaktiviert bestimmte Privilegien und Funktionen
    # https://docs.docker.com/reference/cli/docker/container/run/#security-opt
    security_opt:
      - no-new-privileges:true
    # entfernt alle Linux-Kapazitäten und fügt nur notwendige hinzu
    # https://dockerlabs.collabnix.com/advanced/security/capabilities/
    # https://man7.org/linux/man-pages/man7/capabilities.7.html
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN


    # ----------- Speicher -----------
    # Definiert die Geräte, die dem Container zur Verfügung stehen sollen, und wie sie im Container gemountet werden sollen
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    # Read-Only-Dateisystem
    # docker diff container (https://tmp.bearblog.dev/secure-filesystem-in-docker/)
    # A - added file/directory
    # C - changed file/directory
    # D - deleted file/directory
    # docker exec navidrome du -sh /data
    read_only: true
    # Mountet ein temporäres Dateisystem im Container
    # rw erlaubt Schreibzugriff
    # noexec verhindert die Ausführung von Binärdateien
    # nosuid blockiert das Setzen von SUID/SGID-Bits
    # size begrenzt den verfügbaren Speicherplatz (z.B. 64 MB für /tmp)
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=64m
      - /data:mode=755,uid=1009,gid=1009
      - /run


    # ---------- Environment -----------
    environment:
      TZ: Europe/Berlin
