# https://app.crowdsec.net/hub/author/gauth-fr/collections/immich

# A collection to defend Immich instance against common attacks :
#    Immich parser
#    Immich bruteforce detection

# unter /mnt/user/appdata/traefik/crowdsec/config/acquis.d ablegen

source: docker
container_name:
  - immich
labels:
  type: immich