services:
  ollama:
    container_name: ollama
    image: ollama/ollama:0.18.2@sha256:5a5d014aa774f78ebe1340c0d4afc2e35afc12a2c3b34c84e71f78ea20af4ba3
    pull_policy: always
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - ollama
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.ollama-api.rule: Host(`ollama-api.local.nico-steinmueller.de`)
      traefik.http.routers.ollama-api.entrypoints: websecure
      traefik.http.routers.ollama-api.middlewares: local-only@file
      traefik.http.routers.ollama-api.service: ollama-api
      traefik.http.services.ollama-api.loadbalancer.server.port: 11434

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:0.8.10@sha256:ee057955040ce91e3e787e4b7978c9c23e828972c68d01d787ed40f9a307df9f
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - ollama
    environment:
      TZ: Europe/Berlin
      OLLAMA_BASE_URL: http://ollama:11434
      WEBUI_AUTH: "True"
    ports:
      - "8080:8080"
    volumes:
      - /mnt/user/appdata/ollama/open-webui:/app/backend/data
    networks:
      - ollama
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.open-webui.rule: Host(`ollama.local.nico-steinmueller.de`)
      traefik.http.routers.open-webui.entrypoints: websecure
      traefik.http.routers.open-webui.middlewares: local-only@file
      traefik.http.routers.open-webui.service: open-webui
      traefik.http.services.open-webui.loadbalancer.server.port: 8080

networks:
  ollama:
     name: ollama
  proxy:
    external: true

volumes:
  ollama:

