services:
  uptime-kuma:
    user: 99:100
    networks:
      proxy:
    volumes:
      - type: bind
        source: /mnt/user/appdata/uptime-kuma
        target: /app/data
        read_only: false
        bind:
          create_host_path: false
    labels:
      traefik.enable: true
      traefik.http.routers.uptime-kuma.rule: Host(`uptime-kuma.local.nico-steinmueller.de`)
      traefik.http.routers.uptime-kuma.entrypoints: websecure
      traefik.http.routers.uptime-kuma.middlewares: local-only@file
      traefik.http.routers.uptime-kuma.service: uptime-kuma
      traefik.http.services.uptime-kuma.loadbalancer.server.port: 3001

networks:
  proxy:
    external: true